# ============================
# PERFIL PROD - MySQL en AWS RDS
# Pon aquí tus credenciales de AWS cuando las tengas
# ============================

# Conexión MySQL AWS
spring.datasource.url=jdbc:mysql://TU-ENDPOINT-AWS.rds.amazonaws.com:3306/ruiz_db?useSSL=true&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=TU_USUARIO
spring.datasource.password=TU_CONTRASEÑA
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Dialecto MySQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
