# ============================
# PERFIL DEV - MySQL Railway (conexión pública)
# ============================
spring.datasource.url=jdbc:mysql://interchange.proxy.rlwy.net:51000/railway?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=ZGcSBOfMXZBCVvqXwagfqFBNECLexwUt
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# ============================
# Optimización de conexiones DB (menos RAM en Railway)
# ============================
spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.idle-timeout=300000

# ============================
# Reducir logs (menos CPU)
# ============================
logging.level.root=WARN
logging.level.com.ruiz=INFO
